version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 12
    groups:
      androidx: 
        patterns:
          - "androidx.*"
      tooling:
        patterns:
          - "com.android.application"
          - "org.jetbrains.kotlin.android"
          - "com.diffplug.spotless"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 12
    groups:
      actions: 
        patterns:
          - "*"
