# Copyright (c) 2026 Febrian Rahmad Cahya. All rights reserved.

version: 2
updates:
  - package-ecosystem: gradle
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      android-gradle:
        patterns: ['com.android.tools.build:gradle', 'org.jetbrains.kotlin:*', 'com.google.dagger:*']
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
