ci:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/workflows/**"
          - ".github/actions/**"
          - "scripts/ci/**"
          - "scripts/telegram/**"
build-system:
  - changed-files:
      - any-glob-to-any-file:
          - "*.gradle.kts"
          - "app/*.gradle.kts"
          - "gradle/**"
          - "gradle.properties"
          - "gradlew"
          - "gradlew.bat"
          - "Android.bp"
android:
  - changed-files:
      - any-glob-to-any-file:
          - "app/src/**"
automation:
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**"
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - "*.md"
          - "docs/**"
translations:
  - changed-files:
      - any-glob-to-any-file:
          - "crowdin.yml"
          - "app/src/main/res/values-*/**"
