#!/usr/bin/env bash
# Copyright (c) 2026 Febrian Rahmad Cahya. All rights reserved.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# Native syntax check.
if [[ -n "${JAVA_HOME:-}" && -d "${JAVA_HOME}/include" ]]; then
  JH="${JAVA_HOME}/include"
else
  JAVAC_PATH="$(command -v javac || true)"
  if [[ -z "$JAVAC_PATH" ]]; then
    echo "javac is required for the JNI header syntax check." >&2
    exit 1
  fi
  JAVAC_REAL="$(readlink -f "$JAVAC_PATH")"
  JAVA_HOME_DETECTED="$(cd "$(dirname "$JAVAC_REAL")/.." && pwd)"
  JH="$JAVA_HOME_DETECTED/include"
fi

test -d "$JH"

a=$(printf '%s' app/src/main/cpp/chrona_time.cpp)
b=$(printf '%s' app/src/main/cpp/chrona_clock.cpp)
clang++ -std=c++20 -Wall -Wextra -Werror=return-type -fsyntax-only \
  -I"$JH" -I"$JH/linux" \
  "$a" "$b"
echo "C++ syntax: PASS"

# Android resource reference check.
python3 - <<'PY'
from pathlib import Path
import re

root = Path('app/src/main')
refs = []
for p in root.rglob('*'):
    if p.suffix in {'.kt', '.java'}:
        text = p.read_text(errors='ignore')
        refs += [(*m, str(p)) for m in re.findall(
            r'R\.(string|drawable|layout|xml|mipmap|color|style|id)\.([A-Za-z0-9_]+)',
            text,
        )]

res = {k: set() for k in ['string', 'drawable', 'layout', 'xml', 'mipmap', 'color', 'style', 'id']}
for p in (root / 'res').rglob('*'):
    if not p.is_file():
        continue
    parent = p.parent.name
    if parent.startswith('values') and p.suffix == '.xml':
        text = p.read_text(errors='ignore')
        for kind in res:
            res[kind].update(re.findall(fr'<{kind}\s+[^>]*name="([^"]+)"', text))
    elif parent.split('-')[0] in res:
        res[parent.split('-')[0]].add(p.stem)

missing = sorted({(kind, name, path) for kind, name, path in refs if name not in res[kind]})
if missing:
    raise SystemExit(f'Missing resources: {missing}')
print('Resource references: PASS')
PY

# Copyright coverage check for project-authored source/configuration files.
python3 - <<'PY'
from pathlib import Path

notice = 'Copyright (c) 2026 Febrian Rahmad Cahya'
tracked_extensions = {'.kt', '.java', '.cpp', '.h', '.xml', '.kts', '.pro', '.properties', '.txt', '.yml', '.yaml', '.sh', '.md'}
excluded_extensions = {'.png', '.jar', '.bat'}
excluded_names = {'gradlew', 'gradlew.bat'}
missing = []
checked = 0

for path in Path('.').rglob('*'):
    if not path.is_file() or '.git' in path.parts:
        continue
    if path.name in excluded_names or path.suffix.lower() in excluded_extensions:
        continue
    if path.suffix.lower() not in tracked_extensions and path.name not in {'.gitignore', '.editorconfig', 'CODEOWNERS'}:
        continue
    if path.name == 'gradle-wrapper.properties':
        # This file is generated by Gradle and remains governed by its own upstream tooling terms.
        continue
    checked += 1
    try:
        text = path.read_text(encoding='utf-8')
    except UnicodeDecodeError:
        continue
    if notice not in text:
        missing.append(str(path))

if missing:
    print('Missing copyright headers:')
    print('\n'.join(f'  {p}' for p in missing))
    raise SystemExit(1)

print(f'Copyright coverage: PASS ({checked} project-authored text/config files)')
PY

echo 'Audit completed.'
